# AI Employee Control Plane mise configuration

[tools]
node = "22.20.0"
python = "3.13.7"
pnpm = "10.18.0"
uv = "0.9.2"

[env]
_.file = ".env"
PYTHONUTF8 = "1"
_.path = [
  "{{config_root}}/node_modules/.bin",
  "{{config_root}}/agent/.venv/bin",
  "./bin"
]


[tasks.install]
description = "Install frontend dependencies with pnpm"
run = "pnpm install"

[tasks.agent-deps]
description = "Install Python agent dependencies via uv"
run = "uv pip install -r agent/requirements.txt"

[tasks.dev]
description = "Run Next.js workspace and agent concurrently"
run = "pnpm run dev"

[tasks.ui]
description = "Run the Next.js control plane workspace only"
run = "pnpm run dev:ui"

[tasks.agent]
description = "Start the Gemini ADK FastAPI agent"
run = "./scripts/run-agent.sh"

[tasks.lint]
description = "Lint and type-check the Next.js workspace"
run = "pnpm run lint"

[tasks.test-agent]
description = "Run Gemini ADK agent test suite"
run = "cd agent && python -m pytest tests/ -v"
