name: Supabase Types Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-types:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Supabase CLI
        run: pnpm install -g supabase

      - name: Generate Supabase types
        run: supabase gen types typescript --linked --schema public,storage,graphql_public > supabase/types.ts
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Check if types are up-to-date
        run: |
          git diff --exit-code supabase/types.ts || (echo "Supabase types are out of date. Please run 'supabase gen types typescript --linked --schema public,storage,graphql_public > supabase/types.ts' locally and commit the changes." && exit 1)

      - name: Run TypeScript type check
        run: pnpm tsc --noEmit
