name: Telemetry Audit (Gate G-B)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run telemetry audit
        if: env.SUPABASE_URL != '' && env.SUPABASE_SERVICE_ROLE_KEY != ''
        run: python scripts/audit_telemetry_events.py --gate G-B
      - name: Skip when secrets missing
        if: env.SUPABASE_URL == '' || env.SUPABASE_SERVICE_ROLE_KEY == ''
        run: echo "Supabase secrets not provided; skipping telemetry audit."
